blank_issues_enabled: false
contact_links:
  - name: Question / Discussion
    url: https://github.com/rejigtian/Smart-AI-Bot/discussions
    about: For general questions and discussions, please use Discussions.
